import React from 'react';
import "./globals.css";

export const metadata: Metadata = {
  title: 'CRM with Next',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
